# -*- coding: utf-8 -*-
"""e10map.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jib6uHfDsuSpVdeZIdTzxGtKUTAvzaOo

# Scotland E10 Fuel Price Map — Folium

This notebook:
1. Fetches live E10 petrol prices from all participating retailers in the UK government's open fuel price scheme
2. Filters stations to Scotland only (using latitude/longitude bounding box)
3. Assigns a colour to each station based on a linear scale from cheapest → most expensive
4. Creates an interactive Folium map (OpenStreetMap) with clustered markers showing the raw price

**Data source:** CMA Fuel Finder interim scheme — [gov.uk/guidance/access-fuel-price-data](https://www.gov.uk/guidance/access-fuel-price-data)

> Re-run the notebook at any time to refresh with the latest prices.

## 0 · Configuration
"""

# ── USER SETTINGS ──────────────────────────────────────────────────────────────

# Colour scale: hex colours for cheapest → most expensive
COLOR_LOW  = "#1a9641"   # green  → cheap
COLOR_MID  = "#ffffbf"   # yellow → mid
COLOR_HIGH = "#d7191c"   # red    → expensive

# Number of colour steps in the legend
N_STEPS = 5

# ── SCOTLAND BOUNDING BOX ──────────────────────────────────────────────────────
# Generous bounds — catches all of mainland Scotland + islands
SCOTLAND_LAT_MIN = 54.6
SCOTLAND_LAT_MAX = 60.9
SCOTLAND_LON_MIN = -7.6
SCOTLAND_LON_MAX = -0.7

"""## 1 · Install dependencies"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install requests pandas matplotlib folium --quiet

"""## 2 · Fetch fuel prices from all retailers"""

# ── Step 2: Fetch fuel prices from all retailers ──────────────────────────────
import requests
import pandas as pd
import time

# All participating retailers from the CMA interim scheme
# Source: https://www.gov.uk/guidance/access-fuel-price-data
RETAILER_FEEDS = {
    "Ascona Group":         "https://fuelprices.asconagroup.co.uk/newfuel.json",
    "Asda":                 "https://storelocator.asda.com/fuel_prices_data.json",
    "bp":                   "https://www.bp.com/en_gb/united-kingdom/home/fuelprices/fuel_prices_data.json",
    "Esso Tesco Alliance":  "https://fuelprices.esso.co.uk/latestdata.json",
    "JET Retail UK":        "https://jetlocal.co.uk/fuel_prices_data.json",
    "Karan Retail":         "https://devapi.krlpos.com/integration/live_price/krl",
    "Morrisons":            "https://www.morrisons.com/fuel-prices/fuel.json",
    "Moto":                 "https://moto-way.com/fuel-price/fuel_prices.json",
    "Motor Fuel Group":     "https://fuel.motorfuelgroup.com/fuel_prices_data.json",
    "Rontec":               "https://www.rontec-servicestations.co.uk/fuel-prices/data/fuel_prices_data.json",
    "Sainsbury's":          "https://api.sainsburys.co.uk/v1/exports/latest/fuel_prices_data.json",
    "SGN":                  "https://www.sgnretail.uk/files/data/SGN_daily_fuel_prices.json",
    "Shell":                "https://www.shell.co.uk/fuel-prices-data.html",
    "Tesco":                "https://www.tesco.com/fuel_prices/fuel_prices_data.json"
}

HEADERS = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36",
    "Accept": "application/json, text/plain, */*",
    "Accept-Language": "en-GB,en-US;q=0.9,en;q=0.8",
    "Connection": "keep-alive",
}
TIMEOUT = 15

def parse_station(station: dict, retailer: str) -> dict | None:
    """Extract the fields we need from a station record.
    Returns None if E10 price or coordinates are missing."""
    try:
        fuels = station.get("prices", {})

        # E10 may be keyed as 'E10', 'unleaded', or 'petrol' depending on retailer
        e10 = (
            fuels.get("E10")
            or fuels.get("unleaded")
            or fuels.get("petrol")
        )
        if e10 is None:
            return None

        lat = float(station.get("location", {}).get("latitude", 0)
                    or station.get("lat", 0))
        lon = float(station.get("location", {}).get("longitude", 0)
                    or station.get("lng", 0)
                    or station.get("long", 0))

        if lat == 0 and lon == 0:
            return None

        name = (
            station.get("site_name")
            or station.get("name")
            or station.get("store_name")
            or retailer
        )

        # Grab both address and postcode, then combine them so we can search!
        addr = station.get("address") or ""
        postcode = station.get("postcode") or ""
        address = f"{addr} {postcode}".strip()

        return {
            "name":     name,
            "retailer": retailer,
            "address":  address,
            "lat":      lat,
            "lon":      lon,
            "e10_p":    float(e10),   # price in pence per litre
        }
    except (TypeError, ValueError, KeyError):
        return None

import urllib3
# Suppress the warnings Python throws when you disable SSL verification
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

def fetch_retailer(name: str, url: str) -> list[dict]:
    """Download one retailer feed and return a list of parsed station dicts."""
    try:
        # Added verify=False to bypass expired SSL certificates!
        r = requests.get(url, headers=HEADERS, timeout=TIMEOUT, verify=False)
        r.raise_for_status()
        data = r.json()
    except Exception as e:
        print(f"  ⚠  {name}: skipped ({e})")
        return []

    # Different retailers structure their JSON differently
    stations_raw = (
        data.get("stations")
        or data.get("sites")
        or data.get("store_locations")
        or data.get("data")
        or (data if isinstance(data, list) else [])
    )

    parsed = [parse_station(s, name) for s in stations_raw]
    results = [p for p in parsed if p is not None]
    print(f"  ✓  {name}: {len(results)} stations with E10")
    return results

print("Fetching fuel price data from CMA scheme retailers…")
all_stations = []
for retailer_name, feed_url in RETAILER_FEEDS.items():
    all_stations.extend(fetch_retailer(retailer_name, feed_url))
    time.sleep(0.3)   # be polite

df_all = pd.DataFrame(all_stations)
print(f"\nTotal stations with E10 prices: {len(df_all):,}")

"""## 3 · Filter to Scotland and clean the data"""

# ── Step 3: Filter to Scotland via Postcode and clean the data ──────────────
import re

# Regex pattern for Scottish postcode areas using non-capturing groups (?:)
# Uses a negative lookahead to safely exclude TD12 and TD15 (which are in England).
scotland_regex = r'\b(?:AB|DD|DG|EH|G|HS|IV|KA|KW|KY|ML|PA|PH|TD(?!(?:12|15)\b)|ZE)\d'

# Filter by searching the address column for the postcode pattern (case-insensitive)
df = df_all[
    df_all["address"].str.contains(scotland_regex, flags=re.IGNORECASE, regex=True, na=False)
].copy()

# Sanity check: drop outlier prices (< 50p or > 300p per litre)
df = df[(df["e10_p"] >= 50) & (df["e10_p"] <= 300)]

# If prices are stored as integers (e.g. 14990 = 149.90p), normalise them
if df["e10_p"].median() > 500:
    df["e10_p"] = df["e10_p"] / 100

df = df.drop_duplicates(subset=["lat", "lon"]).reset_index(drop=True)

print(f"Scottish stations found: {len(df)}")
print(f"Price range: {df['e10_p'].min():.1f}p – {df['e10_p'].max():.1f}p per litre")
print(f"Median price: {df['e10_p'].median():.1f}p per litre")
df.head()

"""## 4 · Assign colours based on a linear price scale"""

import matplotlib.colors as mcolors
import matplotlib.pyplot as plt
import numpy as np

# Build a 3-stop linear colour map: green → yellow → red
cmap = mcolors.LinearSegmentedColormap.from_list(
    "fuel_price",
    [COLOR_LOW, COLOR_MID, COLOR_HIGH]
)

price_min = df["e10_p"].min()
price_max = df["e10_p"].max()

def price_to_hex(price: float) -> str:
    """Map a price value linearly onto the colour scale."""
    if price_max == price_min:
        t = 0.5
    else:
        t = (price - price_min) / (price_max - price_min)
    rgba = cmap(t)
    return mcolors.to_hex(rgba)

df["color"] = df["e10_p"].apply(price_to_hex)

# Quick preview of the colour scale
fig, ax = plt.subplots(figsize=(6, 0.6))
gradient = np.linspace(0, 1, 256).reshape(1, -1)
ax.imshow(gradient, aspect="auto", cmap=cmap)
ax.set_xticks([0, 128, 255])
ax.set_xticklabels([f"{price_min:.1f}p", f"{(price_min+price_max)/2:.1f}p", f"{price_max:.1f}p"])
ax.set_yticks([])
ax.set_title("Colour scale: E10 price per litre (pence)")
plt.tight_layout()
plt.show()

print(df[["name", "retailer", "e10_p", "color"]].head(10))

"""## 5 · Generate Interactive Folium Map

This uses OpenStreetMap to plot interactive grouped markers across Scotland. Hovering over a price bubble reveals the station details.
"""

# ── Step 5: Interactive Map ───────────────────────────────────────────────────
import folium
from folium.plugins import MarkerCluster

# Create a base map centered on Scotland using OpenStreetMap
m = folium.Map(
    location=[57.5, -4.0],
    zoom_start=6,
    tiles="CartoDB positron"
)

# Initialize the marker cluster
marker_cluster = MarkerCluster(
    name="E10 Fuel Prices"
).add_to(m)

# Iterate through the dataframe to build markers
for idx, row in df.iterrows():

    # Create a custom HTML icon to display the price directly
    price_html = f"""
    <div style="
        background-color: {row['color']};
        padding: 4px;
        border-radius: 4px;
        border: 1px solid #333;
        font-weight: bold;
        font-family: sans-serif;
        text-align: center;
        width: 45px;
        box-shadow: 2px 2px 4px rgba(0,0,0,0.3);
        font-size: 12px;">
        {row['e10_p']:.1f}p
    </div>
    """

    icon = folium.DivIcon(html=price_html)

    # Build the tooltip content
    tooltip_html = (
        f"<b>{row['name']}</b><br>"
        f"{row['retailer']}<br>"
        f"{row['address']}"
    )

    # Add the marker to the cluster
    folium.Marker(
        location=[row['lat'], row['lon']],
        icon=icon,
        tooltip=tooltip_html
    ).add_to(marker_cluster)

# Display the map inline
m

"""## 6 · Summary statistics"""

import datetime
fetch_date = datetime.datetime.now(datetime.timezone.utc).strftime("%d %B %Y, %H:%M UTC")

print("=" * 50)
print(f"  Scottish stations plotted : {len(df):,}")
print(f"  Cheapest E10              : {df['e10_p'].min():.1f}p  ({df.loc[df['e10_p'].idxmin(), 'name']})")
print(f"  Most expensive E10        : {df['e10_p'].max():.1f}p  ({df.loc[df['e10_p'].idxmax(), 'name']})")
print(f"  Median price              : {df['e10_p'].median():.1f}p")
print(f"  Mean price                : {df['e10_p'].mean():.1f}p")
print("=" * 50)

print("\nStations by retailer:")
print(df["retailer"].value_counts().to_string())

print(f"\n✓ Data fetched: {fetch_date}")

# Save the map as a standalone webpage
m.save("scotland_fuel_map.html")
print("Map successfully updated and saved!")